name: mynodeflow
on:
  issue_comment:
    types: [created, edited]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Use replica action
        uses: chaiforc7/meflow
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
