name: mynodeflow
on: push

jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
  # Configures the node version used on GitHub-hosted runners
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
      # The Node.js version to configure
          node-version: ${{ matrix.node }}
      - name: run stuff
        run:  node index.js
