name: mynodeflow
on:
  - issue_comment:
    types: [created, edited]
  - issues:
    types: opened
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Use replica action
        uses: chaiforc7/meflow@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
