name: mynodeflow2
on: push
jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
          - name: Get Event list
            run: echo '::set-output name=payload::$(cat ${{secrets.GITHUB_EVENT_PATH}})'
            id: content
          - name: Use replica action
            uses: chaiforc7/meflow@main
            with:
              myToken: ${{ secrets.GITHUB_TOKEN }}
              content: ${{ steps.content.outputs.payload}}
