name: mynodeflow2
on: 
  push:
  issue_comment:
    types: [created, edited]
  issues:
    types: opened
 
 
jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
          - name: Get Event list
            run: |
                  path=$(readarray -t path < $GITHUB_EVENT_PATH; IFS=''; echo "${path[*]}")
                  #echo $path
                  echo "::set-output name=payload::$path"
            id: content
          - name: Use replica action
            uses: chaiforc7/meflow@main
            with:
              myToken: ${{ secrets.GITHUB_TOKEN }}
              content: ${{ steps.content.outputs.payload}}
