name: mynodeflow2
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    jobs:
      myjob:
        runs-on: ubuntu-latest
        steps:
          - name: Get Event list
            run: GITHUB_EVENT_PATH
          - name: Use replica action
            uses: chaiforc7/meflow@main
            with:
              myToken: ${{ secrets.GITHUB_TOKEN }}
